### ISSUE TITLE
located((By.XPATH, "//*[@class='icon-button "

### ISSUE THREAD

**Issue by metapodcod** [TreborNamor/TradingView-Machine-Learning-GUI#20]
```
====== WebDriver manager ======
Current firefox version is 91.0.2
Get LATEST driver version for 91.0.2
Driver [C:\Users\metapodcod\.wdm\drivers\geckodriver\win64\v0.29.1\geckodriver.exe] found in cache
Generating Max Profit For Stop Loss.
Loading script...

Traceback (most recent call last):
  File "TradeViewGUI.py", line 122, in optimize_longs_shorts
    if self.comboBox.currentIndex() == 0:
  File "OptimizeLongsShorts.py", line 17, in __init__

  File "OptimizeLongsShorts.py", line 37, in run_script
    # Making sure we are on inputs tab and resetting values to default settings.
  File "my_functions.py", line 32, in click_settings_button
    wait.until(EC.visibility_of_element_located((By.XPATH, "//*[@class='icon-button "
  File "selenium\webdriver\support\wait.py", line 80, in until
selenium.common.exceptions.TimeoutException: Message:

```

**Comment by TreborNamor** [comment]
It looks bot wasn't able to click settings button when running so it
timed out. It could be possible that your profile wasn't automatically
logged in when bot opened up a new Firefox window.
