### ISSUE TITLE
IndexError: list index out of range error

### ISSUE THREAD

**Issue by Samiel77** [TreborNamor/TradingView-Machine-Learning-GUI#28]
Hi,

I ahve the following error:

"Traceback (most recent call last):
  File "TradeViewGUI.py", line 122, in optimize_longs_shorts
    name = obj.objectName()
  File "OptimizeLongsShorts.py", line 17, in __init__
    Main.__init__(self)
  File "OptimizeLongsShorts.py", line 39, in run_script
    except NoSuchElementException:
  File "my_functions.py", line 238, in click_enable_both_checkboxes
    Keys.BACK_SPACE)
IndexError: list index out of range"

can you help please

**Comment by Samiel77** [comment]
Nevermind, working.
forgot to fill the decimal and max attempts...also updated packages.
Thanks
