### ISSUE TITLE
Index List Out of Range

### ISSUE THREAD

**Issue by SWCBTCKid** [TreborNamor/TradingView-Machine-Learning-GUI#29]
====== WebDriver manager ======
Current firefox version is 92.0.1
Get LATEST driver version for 92.0.1
Driver [C:\Users\User\.wdm\drivers\geckodriver\win64\v0.30.0\geckodriver.exe] found in cache
Generating Max Profit For Stop Loss.
Loading script...

Traceback (most recent call last):
  File "TradeViewGUI.py", line 122, in optimize_longs_shorts
    name = obj.objectName()
  File "OptimizeLongsShorts.py", line 17, in __init__
    self.run_script()
  File "OptimizeLongsShorts.py", line 39, in run_script
    self.click_enable_both_checkboxes()
  File "my_functions.py", line 238, in click_enable_both_checkboxes
    long_checkbox = self.driver.find_elements_by_xpath("//*[@class='input-24iGIobO']")[0]
IndexError: list index out of range

looks like i have an issue in the segment of code suppose to read the checkboxes...

**Comment by 0AD0** [comment]
I have the exact same issue, were you able to fix this since?
