### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by KhalidAmine** [TreborNamor/TradingView-Machine-Learning-GUI#46]
Could not click settings button. Please check web_element's in commands.py file.
Could not input tab button. Please check web_element's in commands.py file.
Traceback (most recent call last):
  File "TradeViewGUI.py", line 153, in optimize_longs_shorts
    OptimizeLongsShorts.LongShortScript()
  File "scripts\OptimizeLongsShorts.py", line 21, in __init__
    self.run_script()
  File "scripts\OptimizeLongsShorts.py", line 37, in run_script
    self.click_enable_both_checkboxes()
  File "web_commands\commands.py", line 246, in click_enable_both_checkboxes

IndexError: list index out of range

**Comment by TreborNamor** [comment]
I found that tradingview updated their web elements for the settings button. I  recently updated the web elements to fix this problem I new version
