### ISSUE TITLE
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: .tab-Rf5MOAG5 firefox

### ISSUE THREAD

**Issue by QGB** [TreborNamor/TradingView-Machine-Learning-GUI#60]
```
In [7]: !python C:\test\github\TradingView-Machine-Learning-GUI\TradeViewGUI.py
[WDM] - Downloading: 16.9kB [00:00, 8.03MB/s]
Loading script...

Could Not Click Strategy Tester Tab. Please Check web element's class name in commands.py file.
Could Not click Overview Tab. Please Check web element's class name in commands.py file.
Could not click settings button. Please check web_element's in commands.py file.
Traceback (most recent call last):
  File "C:\test\github\TradingView-Machine-Learning-GUI\TradeViewGUI.py", line 156, in optimize_longs_shorts
    OptimizeLongsShorts.LongShortScript()
  File "C:\test\github\TradingView-Machine-Learning-GUI\scripts\OptimizeLongsShorts.py", line 21, in __init__
    self.run_script()
  File "C:\test\github\TradingView-Machine-Learning-GUI\scripts\OptimizeLongsShorts.py", line 36, in run_script
    self.click_input_tab()
  File "C:\test\github\TradingView-Machine-Learning-GUI\web_commands\commands.py", line 101, in click_input_tab
    input_tab = self.driver.find_element(By.CLASS_NAME, "tab-Rf5MOAG5")
  File "C:\QGB\Anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\QGB\Anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\QGB\Anaconda3\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: .tab-Rf5MOAG5

```

**Comment by durongchun** [comment]
same question
